import { reactive, ref, defineComponent, Fragment, nextTick } from "vue";
import { NEST_CHECKED_LEFT, NEST_CHECKED_RIGHT } from "../config";
import { SwapOutlined, MoreOutlined } from "@ant-design/icons-vue";
import NestTable from "./NestTable.jsx";

export default defineComponent({
  components: {
    SwapOutlined,
    MoreOutlined,
    NestTable,
  },
  props: {},
  setup(props) {
    const columns = [
      {
        title: "菜单名称",
        dataIndex: "name",
        key: "name",
      },
      {
        title: "图标",
        dataIndex: "icon",
        key: "icon",
      },
      {
        title: "菜单类型",
        dataIndex: "type",
        key: "type",
      },
      {
        title: "权限标识",
        dataIndex: "perms",
        key: "perms",
      },
      {
        title: "组件路径",
        dataIndex: "path",
        key: "path",
      },
      {
        title: "状态",
        dataIndex: "status",
        key: "status",
      },
      {
        title: "创建人",
        dataIndex: "createBy",
        key: "createBy",
      },
      {
        title: "创建时间",
        dataIndex: "createTime",
        key: "createTime",
      },
      {
        title: "操作",
        dataIndex: "operate",
        key: "operate",
        width: 250,
      },
    ];

    // *********************
    // Hooks Function
    // *********************

    const data = ref([
      {
        id: "93718d624aaf463c9b2c48998681511a",
        name: "机构管理",
        type: "C",
        pid: "0",
        appCode: "fsse_admin",
        icon: "icon-nav_xtpz",
        perms: null,
        filePath: "321",
        path: "/agency",
        query: null,
        component: "agency",
        sort: 1,
        link: null,
        redirect: null,
        isFrame: null,
        isCache: null,
        isTreeMenu: true,
        status: 1,
        createTime: "2024-10-28 09:32:55",
        updateTime: "2024-10-28 11:07:49",
        createBy: "21312",
        updateBy: "21312",
        children: [
          {
            id: "9570a8e537f74084bbf52c939dbbbfec",
            name: "区域管理",
            type: "C",
            pid: "93718d624aaf463c9b2c48998681511a",
            appCode: "fsse_admin",
            icon: "",
            perms: null,
            filePath: "../pages/agency/region/index.vue",
            path: "/agency/region",
            query: null,
            component: "region",
            sort: 1,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 09:33:36",
            updateTime: "2024-10-30 09:51:31",
            createBy: "21312",
            updateBy: "超级管理员",
            children: null,
          },
          {
            id: "6a1c71f7a72f42919f772841382f0bba",
            name: "机构管理",
            type: "C",
            pid: "93718d624aaf463c9b2c48998681511a",
            appCode: "fsse_admin",
            icon: "",
            perms: null,
            filePath: "../pages/agency/manage/index.vue",
            path: "/agency/manage",
            query: null,
            component: "agency-manage",
            sort: 2,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 09:34:25",
            updateTime: "2024-10-30 09:51:31",
            createBy: "21312",
            updateBy: "超级管理员",
            children: [
              {
                id: "5896a46ec8d64991b09c60e00b604973",
                name: "新增",
                type: "F",
                pid: "6a1c71f7a72f42919f772841382f0bba",
                appCode: "fsse_admin",
                icon: null,
                perms: "agency.manage.add",
                filePath: "null",
                path: "",
                query: null,
                component: "",
                sort: 1,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-28 15:39:47",
                updateTime: "2024-10-28 15:39:47",
                createBy: "21312",
                updateBy: "21312",
                children: null,
              },
              {
                id: "b0292559438f4a8e95119aa93acf7a1a",
                name: "删除",
                type: "F",
                pid: "6a1c71f7a72f42919f772841382f0bba",
                appCode: "fsse_admin",
                icon: null,
                perms: "agency.manage.del",
                filePath: "null",
                path: "",
                query: null,
                component: "",
                sort: 2,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-28 15:40:42",
                updateTime: "2024-10-28 15:40:42",
                createBy: "21312",
                updateBy: "21312",
                children: null,
              },
              {
                id: "2680111e80504db596385e776cd66a25",
                name: "编辑",
                type: "F",
                pid: "6a1c71f7a72f42919f772841382f0bba",
                appCode: "fsse_admin",
                icon: null,
                perms: "agency.manage.edit",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 3,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 09:15:06",
                updateTime: "2024-10-29 09:15:06",
                createBy: "21312",
                updateBy: "21312",
                children: null,
              },
              {
                id: "1a6f6f2fa99348678cc67046838779c2",
                name: "启用/禁用",
                type: "F",
                pid: "6a1c71f7a72f42919f772841382f0bba",
                appCode: "fsse_admin",
                icon: null,
                perms: "agency.manage.enable.disable",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 4,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: true,
                status: 1,
                createTime: "2024-10-29 09:16:17",
                updateTime: "2024-10-29 09:16:17",
                createBy: "21312",
                updateBy: "21312",
                children: null,
              },
              {
                id: "3f0266476b104fd09418c5e5bea8d4cf",
                name: "个性化设置",
                type: "F",
                pid: "6a1c71f7a72f42919f772841382f0bba",
                appCode: "fsse_admin",
                icon: null,
                perms: "agency.manage.personalization",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 5,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 09:17:28",
                updateTime: "2024-10-29 09:17:28",
                createBy: "21312",
                updateBy: "21312",
                children: null,
              },
              {
                id: "f835bf6e8bbc4824aad37b03fdba0366",
                name: "机构详情",
                type: "F",
                pid: "6a1c71f7a72f42919f772841382f0bba",
                appCode: "fsse_admin",
                icon: null,
                perms: "agency.manage.organization.details",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 6,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 09:18:22",
                updateTime: "2024-10-29 09:18:22",
                createBy: "21312",
                updateBy: "21312",
                children: null,
              },
              {
                id: "0968a00bdad940c7bcb66ded9fc8a271",
                name: "账号管理",
                type: "F",
                pid: "6a1c71f7a72f42919f772841382f0bba",
                appCode: "fsse_admin",
                icon: null,
                perms: "agency.manage.account.management",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 7,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 09:19:11",
                updateTime: "2024-10-29 09:19:11",
                createBy: "21312",
                updateBy: "21312",
                children: null,
              },
            ],
          },
          {
            id: "75b9c11f91204c8981bd892c5413168b",
            name: "机构详情",
            type: "C",
            pid: "93718d624aaf463c9b2c48998681511a",
            appCode: "fsse_admin",
            icon: "",
            perms: null,
            filePath: "../pages/agency/info/index.vue",
            path: "/agency/info",
            query: null,
            component: "agency-info",
            sort: 3,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: false,
            status: 1,
            createTime: "2024-10-28 09:34:55",
            updateTime: "2024-10-30 09:51:31",
            createBy: "21312",
            updateBy: "超级管理员",
            children: null,
          },
        ],
      },
      {
        id: "4dc39543cb034c1397eab732ff9fd6b8",
        name: "系统设置",
        type: "C",
        pid: "0",
        appCode: "fsse_admin",
        icon: "icon-xitongguanli",
        perms: null,
        filePath: "null",
        path: "/systemSettings",
        query: null,
        component: "systemSettings",
        sort: 2,
        link: null,
        redirect: null,
        isFrame: null,
        isCache: null,
        isTreeMenu: true,
        status: 1,
        createTime: "2024-10-28 09:35:46",
        updateTime: "2024-10-28 11:07:49",
        createBy: "21312",
        updateBy: "21312",
        children: [
          {
            id: "3aa5b04a79b14fe9ad678aff39b6c601",
            name: "部门管理",
            type: "C",
            pid: "4dc39543cb034c1397eab732ff9fd6b8",
            appCode: "fsse_admin",
            icon: null,
            perms: null,
            filePath: "../pages/systemSettings/organization/index.vue",
            path: "/systemSettings/organization",
            query: null,
            component: "sys_organization",
            sort: 1,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 09:38:57",
            updateTime: "2024-10-28 14:20:59",
            createBy: "21312",
            updateBy: "21312",
            children: [
              {
                id: "8beefdd03d5248c4a5174a6cc7808dbf",
                name: "新增",
                type: "F",
                pid: "3aa5b04a79b14fe9ad678aff39b6c601",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_organization.add",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 1,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:05:51",
                updateTime: "2024-10-30 10:50:08",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "a3c93efadc4845e2b45c767b52035c09",
                name: "删除",
                type: "F",
                pid: "3aa5b04a79b14fe9ad678aff39b6c601",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_organization.del",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 2,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:06:12",
                updateTime: "2024-10-30 10:50:08",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
            ],
          },
          {
            id: "81f6ba276cf9485d9a49c8bbee15b43e",
            name: "角色管理",
            type: "C",
            pid: "4dc39543cb034c1397eab732ff9fd6b8",
            appCode: "fsse_admin",
            icon: null,
            perms: null,
            filePath: "../pages/systemSettings/role/index.vue",
            path: "/systemSettings/role",
            query: null,
            component: "sys_role",
            sort: 2,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 09:38:05",
            updateTime: "2024-10-28 14:20:59",
            createBy: "21312",
            updateBy: "21312",
            children: [
              {
                id: "a69ac00c913f4d6a8b47ea977e057792",
                name: "新增",
                type: "F",
                pid: "81f6ba276cf9485d9a49c8bbee15b43e",
                appCode: "fsse_admin",
                icon: null,
                perms: "sys_role.add",
                filePath: "null",
                path: "",
                query: null,
                component: "",
                sort: 1,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-28 15:17:55",
                updateTime: "2024-10-29 17:34:24",
                createBy: "21312",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "e775937af45e4a169df008210a905abb",
                name: "编辑",
                type: "F",
                pid: "81f6ba276cf9485d9a49c8bbee15b43e",
                appCode: "fsse_admin",
                icon: null,
                perms: "sys_role.edit",
                filePath: "null",
                path: "",
                query: null,
                component: "",
                sort: 2,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-28 15:33:50",
                updateTime: "2024-10-29 17:34:24",
                createBy: "21312",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "50296dab6c794fcb9d6cc4b109204555",
                name: "删除",
                type: "F",
                pid: "81f6ba276cf9485d9a49c8bbee15b43e",
                appCode: "fsse_admin",
                icon: null,
                perms: "sys_role.del",
                filePath: "null",
                path: "",
                query: null,
                component: "",
                sort: 3,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-28 15:28:08",
                updateTime: "2024-10-29 17:34:24",
                createBy: "21312",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "865f34e74eca4d9496c626b9337d168f",
                name: "权限分配",
                type: "F",
                pid: "81f6ba276cf9485d9a49c8bbee15b43e",
                appCode: "fsse_admin",
                icon: null,
                perms: "sys_role.assign",
                filePath: "null",
                path: "",
                query: null,
                component: "",
                sort: 4,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-28 15:36:24",
                updateTime: "2024-10-29 17:34:24",
                createBy: "21312",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "55276ac2a72247c6991829bd976cdd05",
                name: "禁用/启用",
                type: "F",
                pid: "81f6ba276cf9485d9a49c8bbee15b43e",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_role.status",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 5,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:18:15",
                updateTime: "2024-10-29 18:18:15",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
            ],
          },
          {
            id: "acb6e17998f64f289f0eb624de0fb91c",
            name: "菜单配置",
            type: "C",
            pid: "4dc39543cb034c1397eab732ff9fd6b8",
            appCode: "fsse_admin",
            icon: null,
            perms: null,
            filePath: "../pages/systemSettings/menuConfig/index.vue",
            path: "/systemSettings/menuConfig",
            query: null,
            component: "sys_menuConfign",
            sort: 3,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 10:41:16",
            updateTime: "2024-10-28 14:20:59",
            createBy: "21312",
            updateBy: "21312",
            children: [
              {
                id: "1e982cf5072b484bb592377125ae0c6a",
                name: "新增",
                type: "F",
                pid: "acb6e17998f64f289f0eb624de0fb91c",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_menuConfign.add",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 1,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:06:43",
                updateTime: "2024-10-29 18:06:43",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "bbe586339d8b42938d6e5d8ec7629150",
                name: "删除",
                type: "F",
                pid: "acb6e17998f64f289f0eb624de0fb91c",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_menuConfign.del",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 2,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:06:58",
                updateTime: "2024-10-29 18:06:58",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "0a6232db895a44be89a4e507d58dccb1",
                name: "编辑",
                type: "F",
                pid: "acb6e17998f64f289f0eb624de0fb91c",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_menuConfign.edit",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 3,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:20:14",
                updateTime: "2024-10-29 18:20:14",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
            ],
          },
          {
            id: "cea4f147e5024ae187924662226ed6a1",
            name: "用户管理",
            type: "C",
            pid: "4dc39543cb034c1397eab732ff9fd6b8",
            appCode: "fsse_admin",
            icon: null,
            perms: null,
            filePath: "../pages/systemSettings/user/index.vue",
            path: "/systemSettings/user",
            query: null,
            component: "sys_user",
            sort: 4,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 09:40:04",
            updateTime: "2024-10-28 14:20:59",
            createBy: "21312",
            updateBy: "21312",
            children: [
              {
                id: "9a0625eed0f9483c8ec5c08884af1024",
                name: "新增",
                type: "F",
                pid: "cea4f147e5024ae187924662226ed6a1",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_user.add",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 1,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:07:33",
                updateTime: "2024-10-29 18:07:33",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "329d8fab5fbd4e129123db17aa6ec372",
                name: "删除",
                type: "F",
                pid: "cea4f147e5024ae187924662226ed6a1",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_user.del",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 2,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:07:53",
                updateTime: "2024-10-29 18:07:53",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "8f62f39b453b4a7b954b0f713eb251a5",
                name: "编辑",
                type: "F",
                pid: "cea4f147e5024ae187924662226ed6a1",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_user.edit",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 3,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:08:27",
                updateTime: "2024-10-29 18:08:27",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "7ccf1b97ac9c40c4a26abbc4417d2172",
                name: "用户权限",
                type: "F",
                pid: "cea4f147e5024ae187924662226ed6a1",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_user.auth",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 4,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:09:11",
                updateTime: "2024-10-29 18:09:11",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "40d72330157143498e98d64bd200f07b",
                name: "重置",
                type: "F",
                pid: "cea4f147e5024ae187924662226ed6a1",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_user.reset",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 5,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:09:50",
                updateTime: "2024-10-29 18:09:50",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "644897b728554e86b4a7a8dec9787def",
                name: "禁用/启用",
                type: "F",
                pid: "cea4f147e5024ae187924662226ed6a1",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_user.status",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 6,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:25:18",
                updateTime: "2024-10-29 18:25:18",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
            ],
          },
          {
            id: "60d5fdd41055496b9a3e67c1d9391e9a",
            name: "系统配置",
            type: "C",
            pid: "4dc39543cb034c1397eab732ff9fd6b8",
            appCode: "fsse_admin",
            icon: null,
            perms: null,
            filePath: "../pages/systemSettings/sysConfiguration/index.vue",
            path: "/systemSettings/sysConfiguration",
            query: null,
            component: "sys_configuration",
            sort: 5,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 10:42:25",
            updateTime: "2024-10-28 14:20:59",
            createBy: "21312",
            updateBy: "21312",
            children: null,
          },
          {
            id: "03889c26e4ae4cbfa2cff9ad666d0f7f",
            name: "日志管理",
            type: "C",
            pid: "4dc39543cb034c1397eab732ff9fd6b8",
            appCode: "fsse_admin",
            icon: null,
            perms: null,
            filePath: "../pages/systemSettings/log/index.vue",
            path: "/systemSettings/log",
            query: null,
            component: "sys_log",
            sort: 6,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 10:40:42",
            updateTime: "2024-10-28 14:20:59",
            createBy: "21312",
            updateBy: "21312",
            children: null,
          },
          {
            id: "69a7bec3a57b4fdab7505648643c5cab",
            name: "字典管理",
            type: "C",
            pid: "4dc39543cb034c1397eab732ff9fd6b8",
            appCode: "fsse_admin",
            icon: null,
            perms: null,
            filePath: "../pages/systemSettings/dictionaryManaged/index.vue",
            path: "/systemSettings/dictionaryManaged",
            query: null,
            component: "sys_dictionaryManaged",
            sort: 7,
            link: null,
            redirect: null,
            isFrame: null,
            isCache: null,
            isTreeMenu: true,
            status: 1,
            createTime: "2024-10-28 10:41:52",
            updateTime: "2024-10-28 14:20:59",
            createBy: "21312",
            updateBy: "21312",
            children: [
              {
                id: "576da86792154aa0ac88906908203bfd",
                name: "新增",
                type: "F",
                pid: "69a7bec3a57b4fdab7505648643c5cab",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_dictionaryManaged.add",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 1,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:10:49",
                updateTime: "2024-10-29 18:10:49",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "55b36f624fa045cb999b5f58004ee8a0",
                name: "删除",
                type: "F",
                pid: "69a7bec3a57b4fdab7505648643c5cab",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_dictionaryManaged.del",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 2,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:11:05",
                updateTime: "2024-10-29 18:11:05",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "585d361ad0d04523a38f795ec028967d",
                name: "查看",
                type: "F",
                pid: "69a7bec3a57b4fdab7505648643c5cab",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_dictionaryManaged.look",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 3,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:11:27",
                updateTime: "2024-10-29 18:11:27",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
              {
                id: "462355d2de5346c4a79ad37a05cb852f",
                name: "编辑",
                type: "F",
                pid: "69a7bec3a57b4fdab7505648643c5cab",
                appCode: "fsse_admin",
                icon: "",
                perms: "sys_dictionaryManaged.edit",
                filePath: null,
                path: null,
                query: null,
                component: null,
                sort: 4,
                link: null,
                redirect: null,
                isFrame: null,
                isCache: null,
                isTreeMenu: false,
                status: 1,
                createTime: "2024-10-29 18:22:47",
                updateTime: "2024-10-29 18:22:47",
                createBy: "超级管理员",
                updateBy: "超级管理员",
                children: null,
              },
            ],
          },
        ],
      },
    ]);

    const state = reactive({
      expandedRowKeys: [],
      rowSelection: {
        selectedRowKeys: [],
        onChange: (selectedRowKeys, selectedRows) => {
          state.rowSelection.selectedRowKeys = selectedRowKeys;
        },
      },
    });

    // *********************
    // Default Function
    // *********************

    // *********************
    // Life Event Function
    // *********************

    // *********************
    // Service Function
    // *********************

    const start = (evt) => {
    };

    const getChildIds = (data, parentId) => {
      for (let i of data) {
        if (i.id === parentId) {
          return i.children.map((item) => item.id);
        }

        if (i.children) {
          return getChildIds(i.children, parentId);
        }
      }
    };

    const end = (evt) => {
      nextTick(() => {
        let parentId = 0;
        const preSibling = evt.to.previousElementSibling;
        preSibling.classList.forEach((item) => {
          if (item.includes("drag-class")) {
            parentId = item.split("drag-class-")[1];
          }
        });
        let childIds = [];
        if (parentId) {
           childIds = getChildIds(data.value, parentId);
        } else {
          childIds = data.value.map((item) => item.id);
        }

        console.log(data.value);

        console.log("childIds: ", parentId, childIds);
      });
    };

    const move = (evt) => {
    };

    const rowClassName = (record) => {
      return `drag-class-${record.id}`;
    };

    // *********************
    // Render Function
    // *********************

    const slots = {
      [NEST_CHECKED_LEFT]: () => (
        <span class="handle">
          <SwapOutlined />
        </span>
      ),
      [NEST_CHECKED_RIGHT]: () => <MoreOutlined />,
      type: ({ text }) => {
        return text === "C" ? "菜单" : "按钮";
      },
      operate: () => {
        return <button>操作</button>;
      },
    };

    return () => (
      <Fragment>
        <NestTable
          columns={columns}
          v-model={data.value}
          v-model:expandedRowKeys={state.expandedRowKeys}
          handle={".handle"}
          rowSelection={state.rowSelection}
          onStart={start}
          onEnd={end}
          onMove={move}
          rowClassName={rowClassName}
          v-slots={slots}
        ></NestTable>
      </Fragment>
    );
  },
});
